project_name: geoserver-lapaz
description: "ETL pipeline for geospatial data from GeoServer of GAMLP in La Paz, Bolivia"
author: Andres Chirinos
created_date: 2025-06-22
version: 1.0.0

data_dir: "data"
output_dir: "output"

github_actions:
  artifact:
    logs:
      retention_days: 14
    data:
      retention_days: 14

drive:
  folder_id: "1o3tScx8z3WR64uYRG9Qbq_Gfj9IEnWHj"

kaggle:
  dataset_id: "andreschirinos/geoserver-lapaz"
  is_public: true

